input_path: input/data
dims_len: 5 #the number of attributes
for_num: 3
input_num: 60
dims:    #the attributes
    - DOMAIN   #the visited web domain
    - province  #the user location
    - user_type  #the access network type
    - os #the user client type
    - cdn_server #the requested CDN edge server

cut_threshold: 0.001  #the default latent force
topK: 350  #the default search width

con_combine_thr: 0.08  #the default confidence loss

recomm_threshold: 
    confidence: 0.5  #the default confidence